'use strict';

import faker from 'faker';
import Specs from '../../model/specs';
import createMockMotoPromise from './mock-moto';

export default () => {
  const mockData = {};
  return createMockMotoPromise()
    .then((newMotorcycle) => {
      mockData.motorcycle = newMotorcycle;
      /*
      mockData =
        {
          motorcycle: {
            _id: 13089-35985-9 (unique number assigned by mongoose),
            name: some random faker words;
          }
        }
      */
    })
    .then(() => {
      const mockSpecs = {
        style: faker.lorem.words(2),
        cc: faker.random.number(1),
        motorcycleId: mockData.motorcycle._id,
      };
      return new Specs(mockSpecs).save();
    })
    .then((newSpecs) => {
      mockData.specs = newSpecs;

      /*
      mockData =
        {
          motorcycle: {
            _id: 13089-35985-9 (unique number assigned by mongoose),
            name: some random faker words;
          },
          specs: {
            style: some words,
            cc: one word,
            _id: (generated by mongoose),
            motorcycleId: 13089-35985-9,
          }
        }
      */
      return mockData;
    })
    .catch((err) => {
      throw err;
    });
};
